import { StyleSheet, Dimensions, Platform, StatusBar } from "react-native";

const screenWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
const windowWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
  // START SCREEN
  startcontainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5DEB3",
  },
  title: {
    fontSize: 60,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 0,
    marginTop: 20,
    position: "absolute",
    paddingBottom: 350,
    textShadowColor: "#000000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  buttonContainer: {
    width: "80%",
    justifyContent: "space-around",
  },
  customButton: {
    backgroundColor: "#F08080",
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#FFA500",
    marginBottom: 20,
    elevation: 5,
  },
  customButtonText: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  gridContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  gridRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#000",
    opacity: 0.5,
  },
  gridLetter: {
    fontSize: 20,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRightWidth: 0.5,
    borderLeftWidth: 0.5,
    borderColor: "#000",
    borderRadius: 5,
  },

  //GAME SCREEN
  levelTitle: {
    fontSize: 60,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 0,
    marginTop: 20,
    textShadowColor: "#000000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  step: {
    position: 'absolute',
    height: 20,
  },
  main_screen_text: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5DEB3',
  },
  currentWord: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: 0,
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  gridContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: windowWidth * 0.8,
    height: windowWidth * 0.8,
  },
  row: {
    flexDirection: 'row',
  },
  button: (color) => ({
    width: windowWidth * 0.08,
    height: windowWidth * 0.08,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: '#F08080',
    backgroundColor: color,
    borderRadius: 8,
    shadowColor: '#000000',
    shadowOffset: { width: 0.5, height: 0.5 },
    shadowRadius: 1,
    shadowOpacity: 0.85,
    elevation: 2,
  }),
  buttonText: (color) => ({
    fontSize: 15,
    fontWeight: 'bold',
    color: color,
    textShadowColor: "#000000",
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 1,
  }),
  buttonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
    marginTop: 10,
    marginBottom: 10,
  },
  mainContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  validWordsContainer: {
    borderWidth: 1,
    borderColor: 'black',
    width: windowWidth * 0.7,
    height: windowHeight * 0.2,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 5,
    borderColor: '#F08080',
    MaxHeight: windowHeight * 0.4,
    MaxWidth: windowWidth * 0.8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
    marginTop: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0.5, height: 0.5 },
    shadowRadius: 1,
    shadowOpacity: 0.9,
    elevation: 2,
  },
  validWord: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#F08080',
    marginRight: 5,
    marginLeft: 5,
  },
  scoreCounter: {
    position: 'absolute',
    top: windowHeight * 0.05,
    right: windowWidth * 0.05,
    fontSize: 18,
    fontWeight: 'bold',
  },
  progressBarContainer: {
    width: '80%',
    alignSelf: 'center',
    marginTop: 5,
    marginBottom: 5,
    position: 'relative',
  },
  progressBarBackground: {
    backgroundColor: '#F08080',
    borderRadius: 5,
    height: 25,
    borderWidth: 0.4,
    borderColor: '#FFA500',
    shadowColor: '#000000',
    shadowOffset: { width: 0.5, height: 0.5 },
    shadowRadius: 1,
    shadowOpacity: 0.85,
    elevation: 5,
  },
  progressBar: {
    backgroundColor: '#FFA500',
    borderRadius: 5,
    height: 24,
  },
  extraButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
    marginBottom: 20,
  },
  menuButtons: {
    backgroundColor: "#F08080",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: "#FFA500",
    marginBottom: 20,
    elevation: 5,
    marginTop: 10,

  },
  menuButtonText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  enterDeleteButtons: {
    backgroundColor: "#F08080",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: "#FFA500",
    elevation: 4,
  },
  enterDeleteButtonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  homeButton: {
    position: 'absolute', // Add this line
    top: 25, // Adjust as needed
    left: 20, // Adjust as needed
  },
  homeButtonText: {
      fontSize: 25,
      fontWeight: "bold",
      color: "#FFFFFF",
      textAlign: "center",
      textShadowColor: "#000000",
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 5,
  },
  resetButton: {
      position: 'absolute', // Add this line
      top: 10, // Adjust as needed
      right: 10, // Adjust as needed
  },
  resetButtonText: {
      fontSize: 40,
      fontWeight: "bold",
      color: "#FFFFFF",
      textAlign: "center",
      textShadowColor: "#000000",
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 5,
  },
  levelText: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
    position: 'absolute',
    bottom: 10,
    right: 10,
  },
  previousButton: {
    position: 'absolute', // Add this line
    top: windowHeight * 0.65,
    left: windowWidth * 0.03,
  },
  previousButtonText: {
    fontSize: 50,
    fontWeight: "bold",
    color: "#F08080",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  nextButton: {
    position: 'absolute', // Add this line
    top: windowHeight * 0.65,
    right: windowWidth * 0.03,
  },
  nextButtonText: {
    fontSize: 50,
    fontWeight: "bold",
    color: "#F08080",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },

  //SELECT SCREEN
  selectcontainer: {
    flex: 1,
    //gray background
    backgroundColor: "#F5DEB3",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selectButtonContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 65,
    paddingBottom: 50,
  },
  levelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "90%",
    marginBottom: 20,
  },
  levelBox: {
    width: screenWidth * 0.2,
    aspectRatio: 1,
    backgroundColor: "#F08080",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    padding: 0,
    borderWidth: 1,
    borderColor: "#FFA500",
  },
  levelNumber: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  starContainer: {
    marginTop: 5,
    alignItems: "center",
  },
  starRating: {
    fontSize: 20,
    textAlign: "center",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  backButton: {
    backgroundColor: "#F08080",
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: "#FFA500",
    marginBottom: 20,
    elevation: 4,
    marginTop: 10,
  },
  backButtonText: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
});

export default styles;
